[package]
name = "toml_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.9"
fs_extra = "1.2.0"
chrono = "0.4.22"
serde = "1.0.144"
serde_derive = "1.0.144"
